// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWo8k_ov2SPaZG_7DdL9F3EA70FSeW488',
    appId: '1:205775131734:web:3984c264c95e8735b557f7',
    messagingSenderId: '205775131734',
    projectId: 'riverpod-chat-app',
    authDomain: 'riverpod-chat-app.firebaseapp.com',
    storageBucket: 'riverpod-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwxOsgF6E3lukU_D1kCM9ZwJJ8ivV9Is',
    appId: '1:205775131734:android:e27c716f6972379ab557f7',
    messagingSenderId: '205775131734',
    projectId: 'riverpod-chat-app',
    storageBucket: 'riverpod-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN1JoEMgDwKbstooeCJwHoMM8-6MEbIMk',
    appId: '1:205775131734:ios:887050499462f10ab557f7',
    messagingSenderId: '205775131734',
    projectId: 'riverpod-chat-app',
    storageBucket: 'riverpod-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN1JoEMgDwKbstooeCJwHoMM8-6MEbIMk',
    appId: '1:205775131734:ios:887050499462f10ab557f7',
    messagingSenderId: '205775131734',
    projectId: 'riverpod-chat-app',
    storageBucket: 'riverpod-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWo8k_ov2SPaZG_7DdL9F3EA70FSeW488',
    appId: '1:205775131734:web:db8f743210c5db83b557f7',
    messagingSenderId: '205775131734',
    projectId: 'riverpod-chat-app',
    authDomain: 'riverpod-chat-app.firebaseapp.com',
    storageBucket: 'riverpod-chat-app.firebasestorage.app',
  );
}
